# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e1a2746ee7ebd33bc24115226811cf4ba38cde5382cc7a423bc9e657632a9d879fbffbdac67fc88e02c8a8ac0ea5fdc8aed210e6c1a8e7c9b77407e264dd4b

test:
  secret_key_base: c68e1b7c9d4d3c4db2b6de03a289868444d374bdfb61dd943045428c2b274bf00a84a4611ffa77caa9849809e8ddca067969f15fbeda92a6ca003fd4622af561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
